import 'package:flutter/material.dart';
import 'package:pokemon_rainbow_city_app/core/theme/app_color_alias.dart';

/// 색상 테마 정의

/// lightTheme 색상 테마
final ColorScheme lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: AppColorAlias.brandPrimary,
  onPrimary: AppColorAlias.foundationWhite,
  primaryContainer: AppColorAlias.brandLine,
  onPrimaryContainer: AppColorAlias.foundationPrimary,
  secondary: AppColorAlias.brandLine,
  onSecondary: AppColorAlias.foundationPrimary,
  secondaryContainer: AppColorAlias.foundationWhite,
  onSecondaryContainer: AppColorAlias.foundationPrimary,
  tertiary: AppColorAlias.foundationPrimary,
  onTertiary: AppColorAlias.foundationWhite,
  tertiaryContainer: AppColorAlias.foundationWhite,
  onTertiaryContainer: AppColorAlias.foundationPrimary,
  error: Colors.red,
  onError: AppColorAlias.foundationWhite,
  errorContainer: Colors.red.shade100,
  onErrorContainer: Colors.red.shade900,
  surface: AppColorAlias.foundationWhite,
  onSurface: AppColorAlias.foundationPrimary,
  surfaceContainerHighest: AppColorAlias.foundationLine,
  onSurfaceVariant: AppColorAlias.foundationPrimary,
  outline: AppColorAlias.foundationLine,
  outlineVariant: AppColorAlias.foundationLine,
  shadow: Colors.black,
  scrim: Colors.black,
  inverseSurface: AppColorAlias.foundationPrimary,
  onInverseSurface: AppColorAlias.foundationWhite,
  inversePrimary: AppColorAlias.brandPrimary,
  surfaceTint: AppColorAlias.brandPrimary,
);

/// darkTheme 색상 테마
final ColorScheme darkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: AppColorAlias.brandPrimary,
  onPrimary: AppColorAlias.foundationWhite,
  primaryContainer: AppColorAlias.brandLine,
  onPrimaryContainer: AppColorAlias.foundationWhite,
  secondary: AppColorAlias.brandLine,
  onSecondary: AppColorAlias.foundationWhite,
  secondaryContainer: AppColorAlias.foundationPrimary,
  onSecondaryContainer: AppColorAlias.foundationWhite,
  tertiary: AppColorAlias.foundationWhite,
  onTertiary: AppColorAlias.foundationPrimary,
  tertiaryContainer: AppColorAlias.foundationPrimary,
  onTertiaryContainer: AppColorAlias.foundationWhite,
  error: Colors.red,
  onError: AppColorAlias.foundationWhite,
  errorContainer: Colors.red.shade700,
  onErrorContainer: Colors.red.shade50,
  surface: AppColorAlias.foundationPrimary,
  onSurface: AppColorAlias.foundationWhite,
  surfaceContainerHighest: AppColorAlias.foundationLine,
  onSurfaceVariant: AppColorAlias.foundationWhite,
  outline: AppColorAlias.foundationLine,
  outlineVariant: AppColorAlias.foundationLine,
  shadow: Colors.black,
  scrim: Colors.black,
  inverseSurface: AppColorAlias.foundationWhite,
  onInverseSurface: AppColorAlias.foundationPrimary,
  inversePrimary: AppColorAlias.brandPrimary,
  surfaceTint: AppColorAlias.brandPrimary,
);
